# Generated by Django 4.2 on 2023-04-18 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='submissionDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 14, 9, 15, 821398)),
        ),
    ]
