# Generated by Django 4.2 on 2023-04-18 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_alter_verification_submissiondate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='username',
        ),
        migrations.AlterField(
            model_name='verification',
            name='submissionDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 14, 33, 42, 741274)),
        ),
    ]
