# Generated by Django 4.2 on 2023-04-18 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_remove_verification_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='verification',
            name='submissionDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 14, 38, 20, 34904)),
        ),
    ]
